title: "MD. MOSHIUR RAHMAN"
author: "MD. MOSHIUR RAHMAN"
email: "moshiurifty15@gmail.com"
description: "Motivated Computer Science student | Content Reviewer | QAC Intern"
avatar: "/assets/img/profile.jpg"
github_username: MdMoshiurtime
linkedin_username: md-moshiurrahman15
instagram_username: moshiur_ifty15
youtube_channel: MOSHIURRAHMANVLOG
facebook_username: mmrahmanofficial.15
footer_text: "© Copyright 2025 MD. MOSHIUR RAHMAN. Powered by Jekyll with al-folio theme. Hosted by GitHub Pages."